# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: restful_query 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "restful_query"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Aaron Quint"]
  s.date = "2015-02-27"
  s.description = "RestfulQuery provides a simple interface in front of a complex parser to parse specially formatted query hashes into complex SQL queries. It includes ActiveRecord and Sequel extensions."
  s.email = "aaron@quirkey.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Appraisals",
    "Gemfile",
    "History.txt",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "init.rb",
    "lib/restful_query.rb",
    "lib/restful_query/can_query.rb",
    "lib/restful_query/condition.rb",
    "lib/restful_query/parser.rb",
    "lib/restful_query/rails.rb",
    "lib/restful_query/sort.rb",
    "lib/sequel/extensions/restful_query.rb",
    "rails/init.rb",
    "restful_query.gemspec",
    "test/can_query_test.rb",
    "test/condition_test.rb",
    "test/helper.rb",
    "test/parser_test.rb",
    "test/sort_test.rb"
  ]
  s.homepage = "https://github.com/quirkey/restful_query"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Simple ActiveRecord and Sequel queries from a RESTful and safe interface"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.2.0"])
      s.add_runtime_dependency(%q<chronic>, [">= 0.2.3"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
      s.add_development_dependency(%q<minitest>, ["~> 5.5"])
      s.add_development_dependency(%q<shoulda-context>, ["~> 1.2"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.2.0"])
      s.add_dependency(%q<chronic>, [">= 0.2.3"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
      s.add_dependency(%q<minitest>, ["~> 5.5"])
      s.add_dependency(%q<shoulda-context>, ["~> 1.2"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.2.0"])
    s.add_dependency(%q<chronic>, [">= 0.2.3"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
    s.add_dependency(%q<minitest>, ["~> 5.5"])
    s.add_dependency(%q<shoulda-context>, ["~> 1.2"])
  end
end

